#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void gen_date_header(char* dest)
{
    time_t  now;
    char*   datestr;

    time(&now);
    datestr = ctime(&now);

    sprintf(dest, "Date: %s", datestr);
    dest[strlen(dest) - 1] = '\0'; // drop the trailing newline generated by ctime()

    return;
}
